### ISSUE TITLE
Figure 2

### ISSUE THREAD

**Issue by kevinegan31** [niallmm/SINDy_AIC#1]
I was hoping to better understand Figure 2 in the paper. Do you have example code for how Figure 2 was developed for both curves?

**Comment by niallmm** [comment]
Figure 2 is not generated from data. It is purely schematic, based on a conceptual idea of the behavior and has no actual equations underlying it.  So there is no code to develop figure 2. You can roughly see the same behavior in Figures 3c, 4b, 5b, and 6b, all of which can be recreated by running the example files in this codebase.
