### ISSUE TITLE
Identifying Lambda

### ISSUE THREAD

**Issue by kevinegan31** [niallmm/SINDy_AIC#2]
After running the Lorenz code, the results provide the lowest AICc values, how does one identify which lambda/cut off value is related to each AIC/model developed?

Thanks

**Comment by niallmm** [comment]
The coefficients for the model are stored in Xicomb{nn} for 1<nn<N. For the lorenz system N is 30. AIC is calculated for each of these models. The lambdavec contains the lambda values used to generate each Xicomb{nn} (both are output of multiD_Xilib). So lambdavec(nn) should also be 1<nn<N. The nn'th lambdavec entry corresponds to the nn'th Xicomb entry and the nn'th IC or AIC_rel value.
